# Generated by Django 4.1.13 on 2024-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0002_harper_resident"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pets",
            name="make",
        ),
        migrations.RemoveField(
            model_name="pets",
            name="use",
        ),
    ]
