# Generated by Django 4.1.13 on 2024-02-18 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_allottee_name_alter_user_house_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="ID Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="Phone Number"
            ),
        ),
    ]
